///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LabMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 8
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  LabMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  LabMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class LabMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 8
  }
}
*/

  LabMetaPagination? pagination;

  LabMeta({
    this.pagination,
  });
  LabMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? LabMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class LabDataAttributesMIDDataAttributes {
/*
{
  "Name": "احمد شعبان",
  "Job": "فنى مختبر",
  "createdAt": "2022-05-23T20:57:08.467Z",
  "updatedAt": "2022-05-23T20:57:09.670Z",
  "publishedAt": "2022-05-23T20:57:09.666Z"
}
*/

  String? Name;
  String? Job;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  LabDataAttributesMIDDataAttributes({
    this.Name,
    this.Job,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  LabDataAttributesMIDDataAttributes.fromJson(Map<String, dynamic> json) {
    Name = json['Name']?.toString();
    Job = json['Job']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Name'] = Name;
    data['Job'] = Job;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class LabDataAttributesMIDData {
/*
{
  "id": 4,
  "attributes": {
    "Name": "احمد شعبان",
    "Job": "فنى مختبر",
    "createdAt": "2022-05-23T20:57:08.467Z",
    "updatedAt": "2022-05-23T20:57:09.670Z",
    "publishedAt": "2022-05-23T20:57:09.666Z"
  }
}
*/

  int? id;
  LabDataAttributesMIDDataAttributes? attributes;

  LabDataAttributesMIDData({
    this.id,
    this.attributes,
  });
  LabDataAttributesMIDData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? LabDataAttributesMIDDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class LabDataAttributesMID {
/*
{
  "data": {
    "id": 4,
    "attributes": {
      "Name": "احمد شعبان",
      "Job": "فنى مختبر",
      "createdAt": "2022-05-23T20:57:08.467Z",
      "updatedAt": "2022-05-23T20:57:09.670Z",
      "publishedAt": "2022-05-23T20:57:09.666Z"
    }
  }
}
*/

  LabDataAttributesMIDData? data;

  LabDataAttributesMID({
    this.data,
  });
  LabDataAttributesMID.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? LabDataAttributesMIDData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class LabDataAttributes {
/*
{
  "PCnumber": "49",
  "createdAt": "2022-05-23T23:33:42.083Z",
  "updatedAt": "2022-05-23T23:34:01.718Z",
  "publishedAt": "2022-05-23T23:33:43.457Z",
  "LabNumber": "6019",
  "MID": {
    "data": {
      "id": 4,
      "attributes": {
        "Name": "احمد شعبان",
        "Job": "فنى مختبر",
        "createdAt": "2022-05-23T20:57:08.467Z",
        "updatedAt": "2022-05-23T20:57:09.670Z",
        "publishedAt": "2022-05-23T20:57:09.666Z"
      }
    }
  }
}
*/

  String? PCnumber;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  String? LabNumber;
  LabDataAttributesMID? MID;

  LabDataAttributes({
    this.PCnumber,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.LabNumber,
    this.MID,
  });
  LabDataAttributes.fromJson(Map<String, dynamic> json) {
    PCnumber = json['PCnumber']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    LabNumber = json['LabNumber']?.toString();
    MID = (json['MID'] != null) ? LabDataAttributesMID.fromJson(json['MID']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['PCnumber'] = PCnumber;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    data['LabNumber'] = LabNumber;
    if (MID != null) {
      data['MID'] = MID!.toJson();
    }
    return data;
  }
}

class LabData {
/*
{
  "id": 2,
  "attributes": {
    "PCnumber": "49",
    "createdAt": "2022-05-23T23:33:42.083Z",
    "updatedAt": "2022-05-23T23:34:01.718Z",
    "publishedAt": "2022-05-23T23:33:43.457Z",
    "LabNumber": "6019",
    "MID": {
      "data": {
        "id": 4,
        "attributes": {
          "Name": "احمد شعبان",
          "Job": "فنى مختبر",
          "createdAt": "2022-05-23T20:57:08.467Z",
          "updatedAt": "2022-05-23T20:57:09.670Z",
          "publishedAt": "2022-05-23T20:57:09.666Z"
        }
      }
    }
  }
}
*/

  int? id;
  LabDataAttributes? attributes;

  LabData({
    this.id,
    this.attributes,
  });
  LabData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? LabDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class Lab {
/*
{
  "data": [
    {
      "id": 2,
      "attributes": {
        "PCnumber": "49",
        "createdAt": "2022-05-23T23:33:42.083Z",
        "updatedAt": "2022-05-23T23:34:01.718Z",
        "publishedAt": "2022-05-23T23:33:43.457Z",
        "LabNumber": "6019",
        "MID": {
          "data": {
            "id": 4,
            "attributes": {
              "Name": "احمد شعبان",
              "Job": "فنى مختبر",
              "createdAt": "2022-05-23T20:57:08.467Z",
              "updatedAt": "2022-05-23T20:57:09.670Z",
              "publishedAt": "2022-05-23T20:57:09.666Z"
            }
          }
        }
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 8
    }
  }
}
*/

  List<LabData?>? data;
  LabMeta? meta;

  Lab({
    this.data,
    this.meta,
  });
  Lab.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LabData>[];
      v.forEach((v) {
        arr0.add(LabData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? LabMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
