///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LibraryMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 6
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  LibraryMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  LibraryMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class LibraryMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 6
  }
}
*/

  LibraryMetaPagination? pagination;

  LibraryMeta({
    this.pagination,
  });
  LibraryMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? LibraryMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class LibraryDataAttributesBookTypeDataAttributes {
/*
{
  "Type": "Microsoft visual studio",
  "createdAt": "2022-05-21T17:10:31.260Z",
  "updatedAt": "2022-05-28T03:37:02.865Z",
  "publishedAt": "2022-05-21T17:10:32.906Z"
}
*/

  String? Type;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  LibraryDataAttributesBookTypeDataAttributes({
    this.Type,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  LibraryDataAttributesBookTypeDataAttributes.fromJson(Map<String, dynamic> json) {
    Type = json['Type']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Type'] = Type;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class LibraryDataAttributesBookTypeData {
/*
{
  "id": 1,
  "attributes": {
    "Type": "Microsoft visual studio",
    "createdAt": "2022-05-21T17:10:31.260Z",
    "updatedAt": "2022-05-28T03:37:02.865Z",
    "publishedAt": "2022-05-21T17:10:32.906Z"
  }
}
*/

  int? id;
  LibraryDataAttributesBookTypeDataAttributes? attributes;

  LibraryDataAttributesBookTypeData({
    this.id,
    this.attributes,
  });
  LibraryDataAttributesBookTypeData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? LibraryDataAttributesBookTypeDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class LibraryDataAttributesBookType {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "Type": "Microsoft visual studio",
      "createdAt": "2022-05-21T17:10:31.260Z",
      "updatedAt": "2022-05-28T03:37:02.865Z",
      "publishedAt": "2022-05-21T17:10:32.906Z"
    }
  }
}
*/

  LibraryDataAttributesBookTypeData? data;

  LibraryDataAttributesBookType({
    this.data,
  });
  LibraryDataAttributesBookType.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? LibraryDataAttributesBookTypeData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class LibraryDataAttributesAcademicYearDataAttributes {
/*
{
  "Year": "2018/2019",
  "createdAt": "2022-05-21T16:50:27.812Z",
  "updatedAt": "2022-05-23T21:20:29.882Z",
  "publishedAt": "2022-05-21T16:50:33.930Z"
}
*/

  String? Year;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  LibraryDataAttributesAcademicYearDataAttributes({
    this.Year,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  LibraryDataAttributesAcademicYearDataAttributes.fromJson(Map<String, dynamic> json) {
    Year = json['Year']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Year'] = Year;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class LibraryDataAttributesAcademicYearData {
/*
{
  "id": 1,
  "attributes": {
    "Year": "2018/2019",
    "createdAt": "2022-05-21T16:50:27.812Z",
    "updatedAt": "2022-05-23T21:20:29.882Z",
    "publishedAt": "2022-05-21T16:50:33.930Z"
  }
}
*/

  int? id;
  LibraryDataAttributesAcademicYearDataAttributes? attributes;

  LibraryDataAttributesAcademicYearData({
    this.id,
    this.attributes,
  });
  LibraryDataAttributesAcademicYearData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? LibraryDataAttributesAcademicYearDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class LibraryDataAttributesAcademicYear {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "Year": "2018/2019",
      "createdAt": "2022-05-21T16:50:27.812Z",
      "updatedAt": "2022-05-23T21:20:29.882Z",
      "publishedAt": "2022-05-21T16:50:33.930Z"
    }
  }
}
*/

  LibraryDataAttributesAcademicYearData? data;

  LibraryDataAttributesAcademicYear({
    this.data,
  });
  LibraryDataAttributesAcademicYear.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? LibraryDataAttributesAcademicYearData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class LibraryDataAttributes {
/*
{
  "Number": "12",
  "createdAt": "2022-06-11T13:40:02.839Z",
  "updatedAt": "2022-06-11T13:41:49.757Z",
  "publishedAt": "2022-06-11T13:40:02.836Z",
  "academic_year": {
    "data": {
      "id": 1,
      "attributes": {
        "Year": "2018/2019",
        "createdAt": "2022-05-21T16:50:27.812Z",
        "updatedAt": "2022-05-23T21:20:29.882Z",
        "publishedAt": "2022-05-21T16:50:33.930Z"
      }
    }
  },
  "book_type": {
    "data": {
      "id": 1,
      "attributes": {
        "Type": "Microsoft visual studio",
        "createdAt": "2022-05-21T17:10:31.260Z",
        "updatedAt": "2022-05-28T03:37:02.865Z",
        "publishedAt": "2022-05-21T17:10:32.906Z"
      }
    }
  }
}
*/

  String? Number;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  LibraryDataAttributesAcademicYear? academicYear;
  LibraryDataAttributesBookType? bookType;

  LibraryDataAttributes({
    this.Number,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.academicYear,
    this.bookType,
  });
  LibraryDataAttributes.fromJson(Map<String, dynamic> json) {
    Number = json['Number']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    academicYear = (json['academic_year'] != null) ? LibraryDataAttributesAcademicYear.fromJson(json['academic_year']) : null;
    bookType = (json['book_type'] != null) ? LibraryDataAttributesBookType.fromJson(json['book_type']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Number'] = Number;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (academicYear != null) {
      data['academic_year'] = academicYear!.toJson();
    }
    if (bookType != null) {
      data['book_type'] = bookType!.toJson();
    }
    return data;
  }
}

class LibraryData {
/*
{
  "id": 122,
  "attributes": {
    "Number": "12",
    "createdAt": "2022-06-11T13:40:02.839Z",
    "updatedAt": "2022-06-11T13:41:49.757Z",
    "publishedAt": "2022-06-11T13:40:02.836Z",
    "academic_year": {
      "data": {
        "id": 1,
        "attributes": {
          "Year": "2018/2019",
          "createdAt": "2022-05-21T16:50:27.812Z",
          "updatedAt": "2022-05-23T21:20:29.882Z",
          "publishedAt": "2022-05-21T16:50:33.930Z"
        }
      }
    },
    "book_type": {
      "data": {
        "id": 1,
        "attributes": {
          "Type": "Microsoft visual studio",
          "createdAt": "2022-05-21T17:10:31.260Z",
          "updatedAt": "2022-05-28T03:37:02.865Z",
          "publishedAt": "2022-05-21T17:10:32.906Z"
        }
      }
    }
  }
}
*/

  int? id;
  LibraryDataAttributes? attributes;

  LibraryData({
    this.id,
    this.attributes,
  });
  LibraryData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? LibraryDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class Library {
/*
{
  "data": [
    {
      "id": 122,
      "attributes": {
        "Number": "12",
        "createdAt": "2022-06-11T13:40:02.839Z",
        "updatedAt": "2022-06-11T13:41:49.757Z",
        "publishedAt": "2022-06-11T13:40:02.836Z",
        "academic_year": {
          "data": {
            "id": 1,
            "attributes": {
              "Year": "2018/2019",
              "createdAt": "2022-05-21T16:50:27.812Z",
              "updatedAt": "2022-05-23T21:20:29.882Z",
              "publishedAt": "2022-05-21T16:50:33.930Z"
            }
          }
        },
        "book_type": {
          "data": {
            "id": 1,
            "attributes": {
              "Type": "Microsoft visual studio",
              "createdAt": "2022-05-21T17:10:31.260Z",
              "updatedAt": "2022-05-28T03:37:02.865Z",
              "publishedAt": "2022-05-21T17:10:32.906Z"
            }
          }
        }
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 6
    }
  }
}
*/

  List<LibraryData?>? data;
  LibraryMeta? meta;

  Library({
    this.data,
    this.meta,
  });
  Library.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LibraryData>[];
      v.forEach((v) {
        arr0.add(LibraryData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? LibraryMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
