///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StudentDistributionMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 17
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  StudentDistributionMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  StudentDistributionMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class StudentDistributionMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 17
  }
}
*/

  StudentDistributionMetaPagination? pagination;

  StudentDistributionMeta({
    this.pagination,
  });
  StudentDistributionMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? StudentDistributionMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class StudentDistributionDataAttributesGeneral {
/*
{
  "id": 1,
  "Number": "449"
}
*/

  int? id;
  String? Number;

  StudentDistributionDataAttributesGeneral({
    this.id,
    this.Number,
  });
  StudentDistributionDataAttributesGeneral.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    Number = json['Number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Number'] = Number;
    return data;
  }
}

class StudentDistributionDataAttributesNI {
/*
{
  "id": 74,
  "Number": "0"
}
*/

  int? id;
  String? Number;

  StudentDistributionDataAttributesNI({
    this.id,
    this.Number,
  });
  StudentDistributionDataAttributesNI.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    Number = json['Number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Number'] = Number;
    return data;
  }
}

class StudentDistributionDataAttributesAI {
/*
{
  "id": 74,
  "Number": "0"
}
*/

  int? id;
  String? Number;

  StudentDistributionDataAttributesAI({
    this.id,
    this.Number,
  });
  StudentDistributionDataAttributesAI.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    Number = json['Number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Number'] = Number;
    return data;
  }
}

class StudentDistributionDataAttributesIS {
/*
{
  "id": 79,
  "Number": "0"
}
*/

  int? id;
  String? Number;

  StudentDistributionDataAttributesIS({
    this.id,
    this.Number,
  });
  StudentDistributionDataAttributesIS.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    Number = json['Number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Number'] = Number;
    return data;
  }
}

class StudentDistributionDataAttributesCS {
/*
{
  "id": 79,
  "Number": "0"
}
*/

  int? id;
  String? Number;

  StudentDistributionDataAttributesCS({
    this.id,
    this.Number,
  });
  StudentDistributionDataAttributesCS.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    Number = json['Number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['Number'] = Number;
    return data;
  }
}

class StudentDistributionDataAttributesYearDataAttributes {
/*
{
  "Year": "2021/2022",
  "createdAt": "2022-05-23T21:21:16.636Z",
  "updatedAt": "2022-05-23T23:42:26.831Z",
  "publishedAt": "2022-05-23T23:42:26.822Z"
}
*/

  String? Year;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  StudentDistributionDataAttributesYearDataAttributes({
    this.Year,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  StudentDistributionDataAttributesYearDataAttributes.fromJson(Map<String, dynamic> json) {
    Year = json['Year']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Year'] = Year;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class StudentDistributionDataAttributesYearData {
/*
{
  "id": 4,
  "attributes": {
    "Year": "2021/2022",
    "createdAt": "2022-05-23T21:21:16.636Z",
    "updatedAt": "2022-05-23T23:42:26.831Z",
    "publishedAt": "2022-05-23T23:42:26.822Z"
  }
}
*/

  int? id;
  StudentDistributionDataAttributesYearDataAttributes? attributes;

  StudentDistributionDataAttributesYearData({
    this.id,
    this.attributes,
  });
  StudentDistributionDataAttributesYearData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? StudentDistributionDataAttributesYearDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class StudentDistributionDataAttributesYear {
/*
{
  "data": {
    "id": 4,
    "attributes": {
      "Year": "2021/2022",
      "createdAt": "2022-05-23T21:21:16.636Z",
      "updatedAt": "2022-05-23T23:42:26.831Z",
      "publishedAt": "2022-05-23T23:42:26.822Z"
    }
  }
}
*/

  StudentDistributionDataAttributesYearData? data;

  StudentDistributionDataAttributesYear({
    this.data,
  });
  StudentDistributionDataAttributesYear.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? StudentDistributionDataAttributesYearData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class StudentDistributionDataAttributes {
/*
{
  "Level": 1,
  "Male": "400",
  "Female": "49",
  "createdAt": "2022-05-21T17:31:38.974Z",
  "updatedAt": "2022-06-02T16:47:57.525Z",
  "publishedAt": "2022-05-21T17:31:40.352Z",
  "year": {
    "data": {
      "id": 4,
      "attributes": {
        "Year": "2021/2022",
        "createdAt": "2022-05-23T21:21:16.636Z",
        "updatedAt": "2022-05-23T23:42:26.831Z",
        "publishedAt": "2022-05-23T23:42:26.822Z"
      }
    }
  },
  "CS": {
    "id": 79,
    "Number": "0"
  },
  "IS": {
    "id": 79,
    "Number": "0"
  },
  "AI": {
    "id": 74,
    "Number": "0"
  },
  "NI": {
    "id": 74,
    "Number": "0"
  },
  "General": {
    "id": 1,
    "Number": "449"
  }
}
*/

  int? Level;
  String? Male;
  String? Female;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  StudentDistributionDataAttributesYear? year;
  StudentDistributionDataAttributesCS? CS;
  StudentDistributionDataAttributesIS? IS;
  StudentDistributionDataAttributesAI? AI;
  StudentDistributionDataAttributesNI? NI;
  StudentDistributionDataAttributesGeneral? General;

  StudentDistributionDataAttributes({
    this.Level,
    this.Male,
    this.Female,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.year,
    this.CS,
    this.IS,
    this.AI,
    this.NI,
    this.General,
  });
  StudentDistributionDataAttributes.fromJson(Map<String, dynamic> json) {
    Level = json['Level']?.toInt();
    Male = json['Male']?.toString();
    Female = json['Female']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    year = (json['year'] != null) ? StudentDistributionDataAttributesYear.fromJson(json['year']) : null;
    CS = (json['CS'] != null) ? StudentDistributionDataAttributesCS.fromJson(json['CS']) : null;
    IS = (json['IS'] != null) ? StudentDistributionDataAttributesIS.fromJson(json['IS']) : null;
    AI = (json['AI'] != null) ? StudentDistributionDataAttributesAI.fromJson(json['AI']) : null;
    NI = (json['NI'] != null) ? StudentDistributionDataAttributesNI.fromJson(json['NI']) : null;
    General = (json['General'] != null) ? StudentDistributionDataAttributesGeneral.fromJson(json['General']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Level'] = Level;
    data['Male'] = Male;
    data['Female'] = Female;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (year != null) {
      data['year'] = year!.toJson();
    }
    if (CS != null) {
      data['CS'] = CS!.toJson();
    }
    if (IS != null) {
      data['IS'] = IS!.toJson();
    }
    if (AI != null) {
      data['AI'] = AI!.toJson();
    }
    if (NI != null) {
      data['NI'] = NI!.toJson();
    }
    if (General != null) {
      data['General'] = General!.toJson();
    }
    return data;
  }
}

class StudentDistributionData {
/*
{
  "id": 1,
  "attributes": {
    "Level": 1,
    "Male": "400",
    "Female": "49",
    "createdAt": "2022-05-21T17:31:38.974Z",
    "updatedAt": "2022-06-02T16:47:57.525Z",
    "publishedAt": "2022-05-21T17:31:40.352Z",
    "year": {
      "data": {
        "id": 4,
        "attributes": {
          "Year": "2021/2022",
          "createdAt": "2022-05-23T21:21:16.636Z",
          "updatedAt": "2022-05-23T23:42:26.831Z",
          "publishedAt": "2022-05-23T23:42:26.822Z"
        }
      }
    },
    "CS": {
      "id": 79,
      "Number": "0"
    },
    "IS": {
      "id": 79,
      "Number": "0"
    },
    "AI": {
      "id": 74,
      "Number": "0"
    },
    "NI": {
      "id": 74,
      "Number": "0"
    },
    "General": {
      "id": 1,
      "Number": "449"
    }
  }
}
*/

  int? id;
  StudentDistributionDataAttributes? attributes;

  StudentDistributionData({
    this.id,
    this.attributes,
  });
  StudentDistributionData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? StudentDistributionDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class StudentDistribution {
/*
{
  "data": [
    {
      "id": 1,
      "attributes": {
        "Level": 1,
        "Male": "400",
        "Female": "49",
        "createdAt": "2022-05-21T17:31:38.974Z",
        "updatedAt": "2022-06-02T16:47:57.525Z",
        "publishedAt": "2022-05-21T17:31:40.352Z",
        "year": {
          "data": {
            "id": 4,
            "attributes": {
              "Year": "2021/2022",
              "createdAt": "2022-05-23T21:21:16.636Z",
              "updatedAt": "2022-05-23T23:42:26.831Z",
              "publishedAt": "2022-05-23T23:42:26.822Z"
            }
          }
        },
        "CS": {
          "id": 79,
          "Number": "0"
        },
        "IS": {
          "id": 79,
          "Number": "0"
        },
        "AI": {
          "id": 74,
          "Number": "0"
        },
        "NI": {
          "id": 74,
          "Number": "0"
        },
        "General": {
          "id": 1,
          "Number": "449"
        }
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 17
    }
  }
}
*/

  List<StudentDistributionData?>? data;
  StudentDistributionMeta? meta;

  StudentDistribution({
    this.data,
    this.meta,
  });
  StudentDistribution.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <StudentDistributionData>[];
      v.forEach((v) {
        arr0.add(StudentDistributionData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? StudentDistributionMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
