///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StudentActivityMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 5
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  StudentActivityMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  StudentActivityMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class StudentActivityMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 5
  }
}
*/

  StudentActivityMetaPagination? pagination;

  StudentActivityMeta({
    this.pagination,
  });
  StudentActivityMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? StudentActivityMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class StudentActivityDataAttributesYearDataAttributes {
/*
{
  "Year": "2018/2019",
  "createdAt": "2022-05-21T16:50:27.812Z",
  "updatedAt": "2022-05-23T21:20:29.882Z",
  "publishedAt": "2022-05-21T16:50:33.930Z"
}
*/

  String? Year;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  StudentActivityDataAttributesYearDataAttributes({
    this.Year,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  StudentActivityDataAttributesYearDataAttributes.fromJson(Map<String, dynamic> json) {
    Year = json['Year']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Year'] = Year;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class StudentActivityDataAttributesYearData {
/*
{
  "id": 1,
  "attributes": {
    "Year": "2018/2019",
    "createdAt": "2022-05-21T16:50:27.812Z",
    "updatedAt": "2022-05-23T21:20:29.882Z",
    "publishedAt": "2022-05-21T16:50:33.930Z"
  }
}
*/

  int? id;
  StudentActivityDataAttributesYearDataAttributes? attributes;

  StudentActivityDataAttributesYearData({
    this.id,
    this.attributes,
  });
  StudentActivityDataAttributesYearData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? StudentActivityDataAttributesYearDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class StudentActivityDataAttributesYear {
/*
{
  "data": {
    "id": 1,
    "attributes": {
      "Year": "2018/2019",
      "createdAt": "2022-05-21T16:50:27.812Z",
      "updatedAt": "2022-05-23T21:20:29.882Z",
      "publishedAt": "2022-05-21T16:50:33.930Z"
    }
  }
}
*/

  StudentActivityDataAttributesYearData? data;

  StudentActivityDataAttributesYear({
    this.data,
  });
  StudentActivityDataAttributesYear.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? StudentActivityDataAttributesYearData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class StudentActivityDataAttributes {
/*
{
  "Total": "865",
  "Number": "200",
  "Percentage": 23,
  "createdAt": "2022-05-21T17:21:24.367Z",
  "updatedAt": "2022-05-24T00:01:38.983Z",
  "publishedAt": "2022-05-21T17:21:38.176Z",
  "Year": {
    "data": {
      "id": 1,
      "attributes": {
        "Year": "2018/2019",
        "createdAt": "2022-05-21T16:50:27.812Z",
        "updatedAt": "2022-05-23T21:20:29.882Z",
        "publishedAt": "2022-05-21T16:50:33.930Z"
      }
    }
  }
}
*/

  String? Total;
  String? Number;
  String? Percentage;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  StudentActivityDataAttributesYear? Year;

  StudentActivityDataAttributes({
    this.Total,
    this.Number,
    this.Percentage,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.Year,
  });
  StudentActivityDataAttributes.fromJson(Map<String, dynamic> json) {
    Total = json['Total']?.toString();
    Number = json['Number']?.toString();
    Percentage = json['Percentage']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    Year = (json['Year'] != null) ? StudentActivityDataAttributesYear.fromJson(json['Year']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Total'] = Total;
    data['Number'] = Number;
    data['Percentage'] = Percentage;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (Year != null) {
      data['Year'] = Year!.toJson();
    }
    return data;
  }
}

class StudentActivityData {
/*
{
  "id": 1,
  "attributes": {
    "Total": "865",
    "Number": "200",
    "Percentage": 23,
    "createdAt": "2022-05-21T17:21:24.367Z",
    "updatedAt": "2022-05-24T00:01:38.983Z",
    "publishedAt": "2022-05-21T17:21:38.176Z",
    "Year": {
      "data": {
        "id": 1,
        "attributes": {
          "Year": "2018/2019",
          "createdAt": "2022-05-21T16:50:27.812Z",
          "updatedAt": "2022-05-23T21:20:29.882Z",
          "publishedAt": "2022-05-21T16:50:33.930Z"
        }
      }
    }
  }
}
*/

  int? id;
  StudentActivityDataAttributes? attributes;

  StudentActivityData({
    this.id,
    this.attributes,
  });
  StudentActivityData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? StudentActivityDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class StudentActivity {
/*
{
  "data": [
    {
      "id": 1,
      "attributes": {
        "Total": "865",
        "Number": "200",
        "Percentage": 23,
        "createdAt": "2022-05-21T17:21:24.367Z",
        "updatedAt": "2022-05-24T00:01:38.983Z",
        "publishedAt": "2022-05-21T17:21:38.176Z",
        "Year": {
          "data": {
            "id": 1,
            "attributes": {
              "Year": "2018/2019",
              "createdAt": "2022-05-21T16:50:27.812Z",
              "updatedAt": "2022-05-23T21:20:29.882Z",
              "publishedAt": "2022-05-21T16:50:33.930Z"
            }
          }
        }
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 5
    }
  }
}
*/

  List<StudentActivityData?>? data;
  StudentActivityMeta? meta;

  StudentActivity({
    this.data,
    this.meta,
  });
  StudentActivity.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <StudentActivityData>[];
      v.forEach((v) {
        arr0.add(StudentActivityData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? StudentActivityMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
