///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SurveyItemsMetaPagination {
/*
{
  "page": 1,
  "pageSize": 100,
  "pageCount": 1,
  "total": 44
}
*/

  int? page;
  int? pageSize;
  int? pageCount;
  int? total;

  SurveyItemsMetaPagination({
    this.page,
    this.pageSize,
    this.pageCount,
    this.total,
  });
  SurveyItemsMetaPagination.fromJson(Map<String, dynamic> json) {
    page = json['page']?.toInt();
    pageSize = json['pageSize']?.toInt();
    pageCount = json['pageCount']?.toInt();
    total = json['total']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['page'] = page;
    data['pageSize'] = pageSize;
    data['pageCount'] = pageCount;
    data['total'] = total;
    return data;
  }
}

class SurveyItemsMeta {
/*
{
  "pagination": {
    "page": 1,
    "pageSize": 100,
    "pageCount": 1,
    "total": 44
  }
}
*/

  SurveyItemsMetaPagination? pagination;

  SurveyItemsMeta({
    this.pagination,
  });
  SurveyItemsMeta.fromJson(Map<String, dynamic> json) {
    pagination = (json['pagination'] != null) ? SurveyItemsMetaPagination.fromJson(json['pagination']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pagination != null) {
      data['pagination'] = pagination!.toJson();
    }
    return data;
  }
}

class SurveyItemsDataAttributesSurveyDataAttributes {
/*
{
  "sType": "التسهيلات الداعمة للتعليم",
  "createdAt": "2022-05-24T01:25:25.589Z",
  "updatedAt": "2022-05-24T01:25:27.168Z",
  "publishedAt": "2022-05-24T01:25:27.166Z"
}
*/

  String? sType;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  SurveyItemsDataAttributesSurveyDataAttributes({
    this.sType,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  SurveyItemsDataAttributesSurveyDataAttributes.fromJson(Map<String, dynamic> json) {
    sType = json['sType']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sType'] = sType;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class SurveyItemsDataAttributesSurveyData {
/*
{
  "id": 5,
  "attributes": {
    "sType": "التسهيلات الداعمة للتعليم",
    "createdAt": "2022-05-24T01:25:25.589Z",
    "updatedAt": "2022-05-24T01:25:27.168Z",
    "publishedAt": "2022-05-24T01:25:27.166Z"
  }
}
*/

  int? id;
  SurveyItemsDataAttributesSurveyDataAttributes? attributes;

  SurveyItemsDataAttributesSurveyData({
    this.id,
    this.attributes,
  });
  SurveyItemsDataAttributesSurveyData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? SurveyItemsDataAttributesSurveyDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class SurveyItemsDataAttributesSurvey {
/*
{
  "data": {
    "id": 5,
    "attributes": {
      "sType": "التسهيلات الداعمة للتعليم",
      "createdAt": "2022-05-24T01:25:25.589Z",
      "updatedAt": "2022-05-24T01:25:27.168Z",
      "publishedAt": "2022-05-24T01:25:27.166Z"
    }
  }
}
*/

  SurveyItemsDataAttributesSurveyData? data;

  SurveyItemsDataAttributesSurvey({
    this.data,
  });
  SurveyItemsDataAttributesSurvey.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? SurveyItemsDataAttributesSurveyData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class SurveyItemsDataAttributes {
/*
{
  "Description": "تجهيزات المعامل والمختبرات مناسبة لعدد الطلاب وملائمة للغرض التعليمى",
  "createdAt": "2022-05-24T07:19:17.483Z",
  "updatedAt": "2022-05-24T07:19:19.111Z",
  "publishedAt": "2022-05-24T07:19:19.108Z",
  "survey": {
    "data": {
      "id": 5,
      "attributes": {
        "sType": "التسهيلات الداعمة للتعليم",
        "createdAt": "2022-05-24T01:25:25.589Z",
        "updatedAt": "2022-05-24T01:25:27.168Z",
        "publishedAt": "2022-05-24T01:25:27.166Z"
      }
    }
  }
}
*/

  String? Description;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  SurveyItemsDataAttributesSurvey? survey;

  SurveyItemsDataAttributes({
    this.Description,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.survey,
  });
  SurveyItemsDataAttributes.fromJson(Map<String, dynamic> json) {
    Description = json['Description']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    survey = (json['survey'] != null) ? SurveyItemsDataAttributesSurvey.fromJson(json['survey']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Description'] = Description;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (survey != null) {
      data['survey'] = survey!.toJson();
    }
    return data;
  }
}

class SurveyItemsData {
/*
{
  "id": 22,
  "attributes": {
    "Description": "تجهيزات المعامل والمختبرات مناسبة لعدد الطلاب وملائمة للغرض التعليمى",
    "createdAt": "2022-05-24T07:19:17.483Z",
    "updatedAt": "2022-05-24T07:19:19.111Z",
    "publishedAt": "2022-05-24T07:19:19.108Z",
    "survey": {
      "data": {
        "id": 5,
        "attributes": {
          "sType": "التسهيلات الداعمة للتعليم",
          "createdAt": "2022-05-24T01:25:25.589Z",
          "updatedAt": "2022-05-24T01:25:27.168Z",
          "publishedAt": "2022-05-24T01:25:27.166Z"
        }
      }
    }
  }
}
*/

  int? id;
  SurveyItemsDataAttributes? attributes;

  SurveyItemsData({
    this.id,
    this.attributes,
  });
  SurveyItemsData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    attributes = (json['attributes'] != null) ? SurveyItemsDataAttributes.fromJson(json['attributes']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    return data;
  }
}

class SurveyItems {
/*
{
  "data": [
    {
      "id": 22,
      "attributes": {
        "Description": "تجهيزات المعامل والمختبرات مناسبة لعدد الطلاب وملائمة للغرض التعليمى",
        "createdAt": "2022-05-24T07:19:17.483Z",
        "updatedAt": "2022-05-24T07:19:19.111Z",
        "publishedAt": "2022-05-24T07:19:19.108Z",
        "survey": {
          "data": {
            "id": 5,
            "attributes": {
              "sType": "التسهيلات الداعمة للتعليم",
              "createdAt": "2022-05-24T01:25:25.589Z",
              "updatedAt": "2022-05-24T01:25:27.168Z",
              "publishedAt": "2022-05-24T01:25:27.166Z"
            }
          }
        }
      }
    }
  ],
  "meta": {
    "pagination": {
      "page": 1,
      "pageSize": 100,
      "pageCount": 1,
      "total": 44
    }
  }
}
*/

  List<SurveyItemsData?>? data;
  SurveyItemsMeta? meta;

  SurveyItems({
    this.data,
    this.meta,
  });
  SurveyItems.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SurveyItemsData>[];
      v.forEach((v) {
        arr0.add(SurveyItemsData.fromJson(v));
      });
      this.data = arr0;
    }
    meta = (json['meta'] != null) ? SurveyItemsMeta.fromJson(json['meta']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    return data;
  }
}
